{**
 * Copyright 2023 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2023 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *}

<div class="card-block dpdfrance-shipping">
    {if $summary_shipping_address['type'] === 'relay'}
        <h4 class="h5 black">{l s='Informations complémentaires de livraisons DPD France - Livraison en relais Pickup' mod='dpdfrance'}</h4>
        {$summary_shipping_address['name']|escape:'htmlall':'UTF-8'}
        <br>
        {$summary_shipping_address['customer']|escape:'htmlall':'UTF-8'}
        <br>
        {$summary_shipping_address['location']|escape:'htmlall':'UTF-8'}
        <br>
        {$summary_shipping_address['address']|escape:'htmlall':'UTF-8'}
    {else}
        <h4 class="h5 black">{l s='Informations complémentaires de livraisons DPD France - Livraison à domicile Predict sur créneau horaire' mod='dpdfrance'}</h4>
        {$summary_shipping_address['customer']|escape:'htmlall':'UTF-8'}
        <br>
        {$summary_shipping_address['phone']|escape:'htmlall':'UTF-8'}
    {/if}
</div>

<script type="application/javascript">
    $(document).ready(() => {
        {* IF FINAL ORDER SUMMARY OPTION IS ENABLED *}
        let customerShippingAddress = document.querySelector('section #order-summary-content').children[2].children[0].children[0];
        let dpdfranceShippingBlock = document.querySelector('.dpdfrance-shipping');
        customerShippingAddress.appendChild(dpdfranceShippingBlock);
    });
</script>