<?php
/**
 * Copyright 2023 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2023 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
if (!defined('_PS_VERSION_')) {
    exit;
}

/*
 * Configuration du module DPD France
 *
 * Ne modifiez pas ce fichier.
 *
 * Préférez ajouter un fichier defines_custom.inc.php dans le présent dossier
 * dans lequel vous définirez vos valeurs personnalisées pour les constantes
 * définies dans la section CONSTANTES PERSONNALISABLES.
 *
 * Par exemple : define('DPDFRANCE_PDF_FOLDER_PATH', '/path/to/pdf');
 */

define('DPDFRANCE_MODULE_PATH', _PS_MODULE_DIR_ . 'dpdfrance');

if (is_file(DPDFRANCE_MODULE_PATH . '/config/defines_custom.inc.php')) {
    include_once DPDFRANCE_MODULE_PATH . '/config/defines_custom.inc.php';
}

// CONSTANTES PERSONNALISABLES dans defines_custom.inc.php

// Chemin du dossier où seront stockés de manière temporaire les PDF des étiquettes à merger
if (!defined('DPDFRANCE_PDF_FOLDER_PATH')) {
    define('DPDFRANCE_PDF_FOLDER_PATH', DPDFRANCE_MODULE_PATH . '/pdf');
}

// Chemin où sera stockée la clé privée d'encryptage des données sensibles liées au module
if (!defined('DPDFRANCE_PRIVATE_KEY_PATH')) {
    define('DPDFRANCE_PRIVATE_KEY_PATH', DPDFRANCE_MODULE_PATH . '/config/private_key.php');
}

// Utilisation des fonctions suffixées 'Bc' du webservice Eprint
if (!defined('DPDFRANCE_EPRINT_BC')) {
    define('DPDFRANCE_EPRINT_BC', true);
}

// Url du webservice de Lead Time API
if (!defined('DPDFRANCE_LEADTIME_URL')) {
    define('DPDFRANCE_LEADTIME_URL', 'https://api.dpdgroup.com/api/lead-time/v1/zipcodetozipcode');
}

// CONSTANTES RÉSERVÉES AU DÉVELOPPEMENT

// Activer le mode développement
if (!defined('DPDFRANCE_DEV_MODE')) {
    define('DPDFRANCE_DEV_MODE', false);
}

// Switch de développement choisi
if (!defined('DPDFRANCE_DEV_SWITCH')) {
    define('DPDFRANCE_DEV_SWITCH', null);
}

// Utiliser les webservices en environnement de test
if (!defined('DPDFRANCE_DEV_USE_WS_TEST')) {
    define('DPDFRANCE_DEV_USE_WS_TEST', false);
}

// CONSTANTES NON PERSONNALISABLES

// APPLICATION DE LA CONFIGURATION

if (!is_dir(DPDFRANCE_PDF_FOLDER_PATH)) {
    mkdir(DPDFRANCE_PDF_FOLDER_PATH, null, true);
}

if (file_exists(DPDFRANCE_PRIVATE_KEY_PATH)) {
    require_once DPDFRANCE_PRIVATE_KEY_PATH;
}
