{**
 * Copyright 2023 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2023 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *}

<script type="application/javascript">
    var docPath = '{$docs_path|escape:'htmlall':'UTF-8'}';
    {if isset($dpdfrance_dev_badge)}
        var dpdfrance_dev_badge = '{$dpdfrance_dev_badge}';
    {/if}

    $(document).ready(function() {
        if (typeof dpdfrance_dev_badge !== 'undefined') {
            $('h2.page-title').append(dpdfrance_dev_badge);
        }
    })
</script>

<form action="{$form_submit_url|escape:'htmlall':'UTF-8'}" method="post">
    <fieldset>
        <legend>
            <img src="{$img_path|escape:'htmlall':'UTF-8'}admin/admin.png" alt="" title=""/>
            {l s='Settings' mod='dpdfrance'}
        </legend>

        <!-- Tabs header -->
        <div id="dpdfrance_menu">
            <ul id="onglets">
                <li class="bg-main-red" style="background-color: #dc0032">
                    <a id="onglet0" href="javascript:void(0)"
                       onclick="$('#donnees_exp,#modes_transport,#options_supp,#gestion_exp,#gestion_label,#recap').fadeOut(0, function() {literal}{{/literal}$('#accueil').fadeIn('slow');$('#onglet0').parent().css('background-color', '#dc0032');$('#onglet1,#onglet2,#onglet3,#onglet4,#onglet6').parent().css('background-color', '#808285');{literal}}{/literal});">
                        {l s='Start' mod='dpdfrance'}
                    </a>
                </li>
                <li>
                    <a id="onglet1" href="javascript:void(0)"
                       onclick="$('#accueil,#modes_transport,#gestion_label,#options_supp,#gestion_exp,#recap').fadeOut(0, function() {literal}{{/literal}$('#donnees_exp').fadeIn('slow');$('#onglet1').parent().css('background-color', '#dc0032');
                               $('#onglet0,#onglet2,#onglet3,#onglet4,#onglet5,#onglet6').parent().css('background-color', '#808285');{literal}}{/literal});">
                        {l s='Your personal data' mod='dpdfrance'}
                    </a>
                </li>
                <li>
                    <a id="onglet2" href="javascript:void(0)"
                       onclick="$('#accueil,#donnees_exp,#options_supp,#gestion_label,#gestion_exp,#recap').fadeOut(0, function() {literal}{{/literal}$('#modes_transport').fadeIn('slow');$('#onglet2').parent().css('background-color', '#dc0032');
                               $('#onglet1,#onglet0,#onglet3,#onglet4,#onglet5,#onglet6').parent().css('background-color', '#808285');{literal}}{/literal});">
                        {l s='Delivery services' mod='dpdfrance'}
                    </a>
                </li>
                <li>
                    <a id="onglet3" href="javascript:void(0)"
                       onclick="$('#accueil,#donnees_exp,#modes_transport,#gestion_label,#gestion_exp,#recap').fadeOut(0, function() {literal}{{/literal}$('#options_supp').fadeIn('slow');$('#onglet3').parent().css('background-color', '#dc0032');
                               $('#onglet1,#onglet2,#onglet0,#onglet4,#onglet5,#onglet6').parent().css('background-color', '#808285');{literal}}{/literal});">
                        {l s='Advanced settings' mod='dpdfrance'}
                    </a>
                </li>
                <li>
                    <a id="onglet4" href="javascript:void(0)"
                       onclick="$('#accueil,#donnees_exp,#modes_transport,#gestion_label,#options_supp,#recap').fadeOut(0, function() {literal}{{/literal}$('#gestion_exp').fadeIn('slow');$('#onglet4').parent().css('background-color', '#dc0032');
                               $('#onglet1,#onglet2,#onglet3,#onglet0,#onglet5,#onglet6').parent().css('background-color', '#808285');{literal}}{/literal});">
                        {l s='Orders management' mod='dpdfrance'}
                    </a>
                </li>
                <li>
                    <a id="onglet6" href="javascript:void(0)"
                       onclick="$('#accueil,#donnees_exp,#modes_transport,#options_supp,#gestion_label,#gestion_exp').fadeOut(0, function() {literal}{{/literal}$('#recap').fadeIn('slow');$('#onglet6').parent().css('background-color', '#dc0032');
                               $('#onglet1,#onglet2,#onglet3,#onglet4,#onglet5,#onglet0').parent().css('background-color', '#808285');{literal}}{/literal});">
                        {l s='Summary' mod='dpdfrance'}
                    </a>
                </li>
            </ul>
        </div>

        <!-- (#onglet0) Tab Accueil -->
        <div id="accueil" style="display:block;">
            <strong>
                <br/>
                <span class="section_title">{l s='Welcome to DPD' mod='dpdfrance'}</span>
            </strong>
            <br/>
            <div class="notabene" style="font-size:14px;">
                {l s='You must be a DPD France customer to use this module, if not please get in touch with us at ' mod='dpdfrance'}
                <a href="http://www.dpd.fr/nous_contacter_prestashop" target="_blank">www.dpd.fr</a>
            </div>
            <br/>
            <div id="accueil_wrap">
                <div id="documentation" href="javascript:void(0)"
                     onclick="DPDFranceHandleOpenModuleDoc()">
                    <span class="client_title">{l s='Open documentation' mod='dpdfrance'}</span>
                    <div id="documentation_img"></div>
                    <span class="client_subtitle">{l s='Please click here first to access the user manual' mod='dpdfrance'}</span>
                </div>
                <div id="client" href="javascript:void(0)" onclick="$('#onglet1').click();">
                    <span class="client_title">{l s='I\'m already a customer' mod='dpdfrance'}</span>
                    <div id="client_img"></div>
                    <span class="client_subtitle">{l s='Proceed to the plugin configuration' mod='dpdfrance'}</span>
                </div>
                <br/>
            </div>
        </div>

        <!-- (#onglet1) Tab Vos données expéditeur -->
        <div id="donnees_exp" style="display:none;">
            <br/>
            <span class="section_title">{l s='Your personal data' mod='dpdfrance'}</span>
            <br/><br/>
            <div id="donnees_exp_wrap">
                <label>{l s='Company Name' mod='dpdfrance'}</label>
                <div class="margin-form">
                    <input type="text" size="33" name="nom_exp" value="{$nom_exp|escape:'htmlall':'UTF-8'}"/>
                </div>

                <label>{l s='Address 1' mod='dpdfrance'}</label>
                <div class="margin-form">
                    <input type="text" size="33" name="address_exp" value="{$address_exp|escape:'htmlall':'UTF-8'}"/>
                </div>

                <label>{l s='Address 2' mod='dpdfrance'}</label>
                <div class="margin-form">
                    <input type="text" size="33" name="address2_exp" value="{$address2_exp|escape:'htmlall':'UTF-8'}"/>
                </div>

                <label>{l s='Postal code' mod='dpdfrance'}</label>
                <div class="margin-form">
                    <input type="text" size="33" name="cp_exp" value="{$cp_exp|escape:'htmlall':'UTF-8'}"/>
                </div>

                <label>{l s='City' mod='dpdfrance'}</label>
                <div class="margin-form">
                    <input type="text" size="33" name="ville_exp" value="{$ville_exp|escape:'htmlall':'UTF-8'}"/>
                </div>

                <label>{l s='Telephone' mod='dpdfrance'}</label>
                <div class="margin-form">
                    <input type="text" size="33" name="tel_exp" value="{$tel_exp|escape:'htmlall':'UTF-8'}"/>
                </div>

                <label>{l s='GSM' mod='dpdfrance'}</label>
                <div class="margin-form">
                    <input type="text" size="33" name="gsm_exp" value="{$gsm_exp|escape:'htmlall':'UTF-8'}"/>
                </div>

                <label>{l s='E-mail' mod='dpdfrance'}</label>
                <div class="margin-form">
                    <input type="text" size="33" name="email_exp" value="{$email_exp|escape:'htmlall':'UTF-8'}"/>
                </div>

                <div class="text-center">
                    <a size="6" class="button" href="javascript:void(0)" onclick="$('#onglet0').click();">
                        {l s='Previous' mod='dpdfrance'}
                    </a>
                    <a size="6" class="button" href="javascript:void(0)" onclick="$('#onglet2').click();">
                        {l s='Next' mod='dpdfrance'}
                    </a>
                </div>

                <br/>
            </div>
        </div>

        <!-- (#onglet2) Tab Services de transport -->
        <div id="modes_transport" style="display:none;">
            <br/>
            <span class="section_title">{l s='Delivery services' mod='dpdfrance'}</span>
            <br/><br/>
            <div id="modes_transport_wrap">

                <!-- DPD Relais -->
                <div id="service_relais">
                    <label>{l s='DPD Relais' mod='dpdfrance'} {l s='(France)' mod='dpdfrance'}</label>
                    <div id="service_relais_img"></div>

                    <div id="service_relais_contract">
                        {l s='Depot code - Contract number' mod='dpdfrance'}
                        <br/>
                        {l s='(i.e.: 013 - 12345)' mod='dpdfrance'}
                        <br/><br/>
                        <input type="text" size="4" maxlength="4" name="relais_depot_code" class="relais_depot_code"
                               value="{$relais_depot_code|escape:'htmlall':'UTF-8'}"/> -
                        <input type="text" size="8" maxlength="8" name="relais_shipper_code" class="relais_shipper_code"
                               value="{$relais_shipper_code|escape:'htmlall':'UTF-8'}"/>
                        <br/><br/>
                    </div>
                    <div id="service_next_img"></div>
                    <div id="service_relais_addcarrier">
                        {l s='Carrier creation' mod='dpdfrance'}<br/><br/>
                        <input type="submit" name="submitCreateCarrierRelais"
                               value="{l s='Create DPD Relais carrier' mod='dpdfrance'}" class="button"/>
                    </div>
                    <div id="service_next_img"></div>
                    <div id="service_relais_selectcarrier">
                        {l s='Carrier assignation' mod='dpdfrance'}<br/><br/>
                        <select name="dpdfrance_relais_carrier_id">
                            <option value="0">{l s='None - Disable this carrier' mod='dpdfrance'}</option>
                            {foreach from=$carriers item=carrier}
                                {if $carrier.id_carrier == $dpdfrance_relais_carrier_id}
                                    <option value="{$carrier.id_carrier|escape:'htmlall':'UTF-8'}" selected>
                                        {$carrier.id_carrier|escape:'htmlall':'UTF-8'}
                                        - {$carrier.name|escape:'htmlall':'UTF-8'}
                                    </option>
                                {else}
                                    <option value="{$carrier.id_carrier|escape:'htmlall':'UTF-8'}">
                                        {$carrier.id_carrier|escape:'htmlall':'UTF-8'}
                                        - {$carrier.name|escape:'htmlall':'UTF-8'}
                                    </option>
                                {/if}
                            {/foreach}
                        </select>
                    </div>
                </div>
                <br/>

                <!-- DPD Predict -->
                <div id="service_predict">
                    <label>{l s='DPD Predict' mod='dpdfrance'}</label>
                    <div id="service_predict_img"></div>

                    <div id="service_predict_contract">
                        {l s='Depot code - Contract number' mod='dpdfrance'}
                        <br/>{l s='(i.e.: 013 - 12345)' mod='dpdfrance'}<br/><br/>
                        <input type="text" size="4" maxlength="4" name="predict_depot_code" class="predict_depot_code"
                               value="{$predict_depot_code|escape:'htmlall':'UTF-8'}"/> -
                        <input type="text" size="8" maxlength="8" name="predict_shipper_code"
                               class="predict_shipper_code"
                               value="{$predict_shipper_code|escape:'htmlall':'UTF-8'}"/>
                        <br/><br/>
                    </div>
                    <div id="service_next_img"></div>
                    <div id="service_predict_addcarrier">
                        {l s='Carrier creation' mod='dpdfrance'}<br/><br/>
                        <input type="submit" name="submitCreateCarrierPredict"
                               value="{l s='Create DPD Predict carrier' mod='dpdfrance'}" class="button"/>
                    </div>
                    <div id="service_next_img"></div>
                    <div id="service_predict_selectcarrier">
                        {l s='Carrier assignation' mod='dpdfrance'}<br/><br/>
                        <select name="dpdfrance_predict_carrier_id">
                            <option value="0">{l s='None - Disable this carrier' mod='dpdfrance'}</option>
                            {foreach from=$carriers item=carrier}
                                {if $carrier.id_carrier == $dpdfrance_predict_carrier_id}
                                    <option value="{$carrier.id_carrier|escape:'htmlall':'UTF-8'}" selected>
                                        {$carrier.id_carrier|escape:'htmlall':'UTF-8'}
                                        - {$carrier.name|escape:'htmlall':'UTF-8'}
                                    </option>
                                {else}
                                    <option value="{$carrier.id_carrier|escape:'htmlall':'UTF-8'}">
                                        {$carrier.id_carrier|escape:'htmlall':'UTF-8'}
                                        - {$carrier.name|escape:'htmlall':'UTF-8'}
                                    </option>
                                {/if}
                            {/foreach}
                        </select>
                    </div>
                </div>
                <br/>

                <!-- DPD Classic -->
                <div id="service_classic">
                    <label>{l s='DPD Classic' mod='dpdfrance'}<br/>
                        {l s='Europe & Intercontinental' mod='dpdfrance'} {l s='(France : delivery at workplace)' mod='dpdfrance'}
                    </label>

                    <div id="service_classic_img"></div>

                    <div id="service_classic_contract">
                        {l s='Depot code - Contract number' mod='dpdfrance'}
                        <br/>{l s='(i.e.: 013 - 12345)' mod='dpdfrance'}<br/><br/>
                        <input type="text" size="4" maxlength="4" name="classic_depot_code" class="classic_depot_code"
                               value="{$classic_depot_code|escape:'htmlall':'UTF-8'}"/> -
                        <input type="text" size="8" maxlength="8" name="classic_shipper_code"
                               class="classic_shipper_code" value="{$classic_shipper_code|escape:'htmlall':'UTF-8'}"/>
                        <br/><br/>
                    </div>
                    <div id="service_next_img"></div>
                    <div id="service_classic_addcarrier">
                        {l s='Carrier creation' mod='dpdfrance'}<br/><br/>
                        <input type="submit" name="submitCreateCarrierClassic"
                               value="{l s='Create DPD Classic carrier' mod='dpdfrance'}" class="button"/><br/>
                        <input type="submit" name="submitCreateCarrierWorld"
                               value="{l s='Create DPD Intercontinental carrier' mod='dpdfrance'}" class="button"/><br/>
                    </div>
                    <div id="service_next_img"></div>
                    <div id="service_classic_selectcarrier">
                        {l s='Carrier assignation' mod='dpdfrance'}<br/><br/>
                        <select name="dpdfrance_classic_carrier_id">
                            <option value="0">{l s='None - Disable this carrier' mod='dpdfrance'}</option>
                            {foreach from=$carriers item=carrier}
                                {if $carrier.id_carrier == $dpdfrance_classic_carrier_id}
                                    <option value="{$carrier.id_carrier|escape:'htmlall':'UTF-8'}" selected>
                                        {$carrier.id_carrier|escape:'htmlall':'UTF-8'}
                                        - {$carrier.name|escape:'htmlall':'UTF-8'}
                                    </option>
                                {else}
                                    <option value="{$carrier.id_carrier|escape:'htmlall':'UTF-8'}">
                                        {$carrier.id_carrier|escape:'htmlall':'UTF-8'}
                                        - {$carrier.name|escape:'htmlall':'UTF-8'}
                                    </option>
                                {/if}
                            {/foreach}
                        </select>
                    </div>

                </div>

                <div class="notabene">{l s='Please contact your DPD sales representative to get your contract numbers and depot code.' mod='dpdfrance'}</div>
                <br/><br/>

                <div class="text-center">
                    <a size="6" class="button" href="javascript:void(0)"
                       onclick="$('#onglet1').click();">
                        {l s='Previous' mod='dpdfrance'}</a>
                    <a size="6" class="button" href="javascript:void(0)"
                       onclick="$('#onglet3').click();">
                        {l s='Next' mod='dpdfrance'}</a>
                </div>
                <br/>
            </div>
        </div>

        <!-- (#onglet3) Tab Options supplémentaires -->
        <div id="options_supp" style="display:none;">
            <br/><span class="section_title_alt">{l s='Advanced settings' mod='dpdfrance'}</span><br/><br/>

            <label>{l s='DPD Relais WebService URL' mod='dpdfrance'}</label>
            <div class="margin-form">
                <input type="text" size="48" name="mypudo_url" value="{$mypudo_url|escape:'htmlall':'UTF-8'}"/>
                <br/>
                <a class="main-red" style="font-size: 12px;" href="javascript:void(0)"
                   onclick="DPDFranceHandleOpenModuleDoc(true)">
                    {l s='Caution! Critical setting' mod='dpdfrance'}
                </a>
            </div>

            <label>{l s='Coastal islands & Corsica overcost' mod='dpdfrance'}</label>
            <div class="margin-form">
                <input type="text" size="3" name="supp_iles" value="{$supp_iles|escape:'htmlall':'UTF-8'}"/>
                {l s=' € (-1 to disable delivery to these areas)' mod='dpdfrance'}
            </div>
            <br/>
            <label>{l s='Mountain areas overcost' mod='dpdfrance'}</label>
            <div class="margin-form">
                <input type="text" size="3" name="supp_montagne" value="{$supp_montagne|escape:'htmlall':'UTF-8'}"/>
                {l s=' € (-1 to disable delivery to these areas)' mod='dpdfrance'}
            </div>
            <br/>
            <label>{l s='Google Maps API Key' mod='dpdfrance'}</label>
            <div class="margin-form">
                {if empty($dpdfrance_google)}
                    <input type="text" size="48" name="google_api_key" placeholder="{l s='Clé api privé' mod='dpdfrance'}"/>
                {else}
                    <input type="text" size="48" name="google_api_key" class="dpd_configured" placeholder="{l s='Information prise en compte' mod='dpdfrance'}"/>
                {/if}
                <br/>
                <a href="https://console.developers.google.com/flows/enableapi?apiid=maps_backend,geocoding_backend,directions_backend,distance_matrix_backend,elevation_backend,places_backend&keyType=CLIENT_SIDE&reusekey=true"
                   target="_blank">
                    {l s='Click here to retrieve your Google API Key' mod='dpdfrance'}
                </a>
            </div>
            <br/>

            <br/><br/>
            <span>
                <strong>{l s='Leadtime config' mod='dpdfrance'}</strong>
            </span>
            <br/><br/>

            <label>{l s='DPD Day Definite service' mod='dpdfrance'}</label>
            <div class="margin-form">
                <select name="day_definite_mode">
                    {foreach from=$option_day_definite item=option key=key}
                        {if $key == $day_definite_mode}
                            <option value="{$key|escape:'htmlall':'UTF-8'}"
                                    selected>{$option|escape:'htmlall':'UTF-8'}</option>
                        {else}
                            <option value="{$key|escape:'htmlall':'UTF-8'}">{$option|escape:'htmlall':'UTF-8'}</option>
                        {/if}
                    {/foreach}
                </select>
            </div>
            <div id="leadtime_config">
                <label>{l s='Clé API Lead Time' mod='dpdfrance'}</label>
                <div class="margin-form">
                    {if empty($dpdfrance_leadtime)}
                        <input type="text" size="48" name="leadtime_api_key" placeholder="{l s='Clé api privé' mod='dpdfrance'}"/>
                    {else}
                        <input type="text" size="48" name="leadtime_api_key" class="dpd_configured" placeholder="{l s='Information prise en compte' mod='dpdfrance'}"/>
                    {/if}
                </div>
            </div>

            <br/><br/>
            <span><strong>{l s='Api Login Explain' mod='dpdfrance'}</strong></span>
            <br/><br/>

            <label>{l s='Login Api' mod='dpdfrance'}</label>
            <div class="margin-form">
                <input type="text" size="48" name="api_login" value="{$api_login|escape:'htmlall':'UTF-8'}"/>
            </div>
            <label>{l s='Password Api' mod='dpdfrance'}</label>
            <div class="margin-form">
                {* On n'affiche pas les mots de passe enregistrés dans les formulaires *}
                {if empty($dpdfrance_api)}
                    <input type="password" size="48" name="api_password" placeholder="{l s='Mot de passe privé' mod='dpdfrance'}"/>
                {else}
                    <input type="password" size="48" name="api_password" class="dpd_configured" placeholder="{l s='Information prise en compte' mod='dpdfrance'}"/>
                {/if}
            </div>

            <br/><br/>
            <span><strong>{l s='Webtrace config' mod='dpdfrance'}</strong></span>
            <br/><br/>

            <label>{l s='Login Webtrace' mod='dpdfrance'}</label>
            <div class="margin-form">
                <input type="text" size="48" name="webtrace_login" value="{$webtrace_login|escape:'htmlall':'UTF-8'}"/>
            </div>
            <label>{l s='Password Webtrace' mod='dpdfrance'}</label>
            <div class="margin-form">
                {if empty($dpdfrance_webtrace)}
                    <input type="password" size="48" name="webtrace_password" placeholder="{l s='Mot de passe privé' mod='dpdfrance'}"/>
                {else}
                    <input type="password" size="48" name="webtrace_password" class="dpd_configured" placeholder="{l s='Information prise en compte' mod='dpdfrance'}"/>
                {/if}
            </div>

            <div class="text-center">
                <a size="6" class="button" href="javascript:void(0)" onclick="$('#onglet2').click();">
                    {l s='Previous' mod='dpdfrance'}
                </a>
                <a size="6" class="button" href="javascript:void(0)" onclick="$('#onglet4').click();">
                    {l s='Next' mod='dpdfrance'}
                </a>
            </div>
            <br/>
        </div>

        <!-- (#onglet4) Tab Gestion des expéditions -->
        <div id="gestion_exp" style="display:none;">
            <br/>
            <span class="section_title_alt">{l s='Orders management' mod='dpdfrance'}</span>
            <br/><br/>
            <label>{l s='Preparation in progress status' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select name="id_expedition">
                    {foreach from=$etats_factures item=value}
                        {if $value.id_order_state == $dpdfrance_etape_expedition}
                            <option value="{$value.id_order_state|escape:'htmlall':'UTF-8'}" selected>
                                {$value.name|escape:'htmlall':'UTF-8'}
                            </option>
                        {else}
                            <option value="{$value.id_order_state|escape:'htmlall':'UTF-8'}">{$value.name|escape:'htmlall':'UTF-8'}</option>
                        {/if}
                    {/foreach}
                </select>
                <br/>{l s='Orders in this state will be selected by default for exporting.' mod='dpdfrance'}<br/>
            </div>

            <label>{l s='Shipped status' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select name="id_expedie">
                    {foreach from=$etats_factures item=value}
                        {if $value.id_order_state == $dpdfrance_etape_expediee}
                            <option value="{$value.id_order_state|escape:'htmlall':'UTF-8'}" selected>
                                {$value.name|escape:'htmlall':'UTF-8'}
                            </option>
                        {else}
                            <option value="{$value.id_order_state|escape:'htmlall':'UTF-8'}">
                                {$value.name|escape:'htmlall':'UTF-8'}
                            </option>
                        {/if}
                    {/foreach}
                </select>
                <br/>{l s='Once parcel trackings are generated, orders will be updated to this state.' mod='dpdfrance'}
                <br/>
            </div>

            <label>{l s='Delivered status' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select name="id_livre">
                    {foreach from=$etats_factures item=value}
                        {if $value.id_order_state == $dpdfrance_etape_livre}
                            <option value="{$value.id_order_state|escape:'htmlall':'UTF-8'}" selected>
                                {$value.name|escape:'htmlall':'UTF-8'}
                            </option>
                        {else}
                            <option value="{$value.id_order_state|escape:'htmlall':'UTF-8'}">
                                {$value.name|escape:'htmlall':'UTF-8'}
                            </option>
                        {/if}
                    {/foreach}
                </select>
                <br/>{l s='Once parcels are delivered, orders will be updated to this state.' mod='dpdfrance'}<br/>
            </div>

            <label>{l s='Auto update of status and tracking links' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select name="auto_update">
                    {foreach from=$option_auto_update item=option key=key}
                        {if $key == $auto_update}
                            <option value="{$key|escape:'htmlall':'UTF-8'}" selected>
                                {$option|escape:'htmlall':'UTF-8'}
                            </option>
                        {else}
                            <option value="{$key|escape:'htmlall':'UTF-8'}">
                                {$option|escape:'htmlall':'UTF-8'}
                            </option>
                        {/if}
                    {/foreach}
                </select>
                <br/>
                {l s='Order statuses and tracking links will be automatically updated following parcel delivery.' mod='dpdfrance'}
                <br/>
            </div>

            <label>{l s='Allow management of non-DPD orders' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select name="marketplace_mode">
                    {foreach from=$option_marketplace item=option key=key}
                        {if $key == $marketplace_mode}
                            <option value="{$key|escape:'htmlall':'UTF-8'}"
                                    selected>{$option|escape:'htmlall':'UTF-8'}</option>
                        {else}
                            <option value="{$key|escape:'htmlall':'UTF-8'}">{$option|escape:'htmlall':'UTF-8'}</option>
                        {/if}
                    {/foreach}
                </select>
                <br/>{l s='All orders will be manageable regardless of the carrier, useful when using marketplace connectors.' mod='dpdfrance'}
                <br/>
            </div>

            <label>{l s='Parcel insurance service' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select name="ad_valorem">
                    {foreach from=$option_vd item=option key=key}
                        {if $key == $dpdfrance_ad_valorem}
                            <option value="{$key|escape:'htmlall':'UTF-8'}"
                                    selected>{$option|escape:'htmlall':'UTF-8'}</option>
                        {else}
                            <option value="{$key|escape:'htmlall':'UTF-8'}">{$option|escape:'htmlall':'UTF-8'}</option>
                        {/if}
                    {/foreach}
                </select>
                <br/>{l s='Ad Valorem : Please refer to your pricing conditions.' mod='dpdfrance'}<br/>
            </div>

            <label>{l s='DPD Returns service' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select name="retour">
                    {foreach from=$option_retour item=option key=key}
                        {if $key == $dpdfrance_retour_option}
                            <option value="{$key|escape:'htmlall':'UTF-8'}"
                                    selected>{$option|escape:'htmlall':'UTF-8'}</option>
                        {else}
                            <option value="{$key|escape:'htmlall':'UTF-8'}">{$option|escape:'htmlall':'UTF-8'}</option>
                        {/if}
                    {/foreach}
                </select>
                <br/>{l s='DPD Returns options : Please refer to your pricing conditions.' mod='dpdfrance'}<br/>
            </div>

            <label>{l s='Service : ' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select name="service_type" id="services">
                    <option value="station_dat" {if $service_type == "station_dat" || empty($service_type) } selected="selected"{/if}>{l s='Station' mod='dpdfrance'}</option>
                    <option value="e_print" {if $service_type == "e_print" } selected="selected"{/if}>{l s='E Print.' mod='dpdfrance'}</option>
                </select>
                <br/>{l s='E print need products with weight.' mod='dpdfrance'}<br/>
            </div>

            <div class="margin-form" style="display: none;">
                <select name="format_hide_network" id="hide_network" value="true">
                    <option value=""
                            {if $format_hide_network != 'true'}selected="selected"{/if}>{l s='Hiden' mod='dpdfrance'}</option>
                    <option value="true"
                            {if $format_hide_network == 'true'}selected="selected"{/if}>{l s='No hiden' mod='dpdfrance'}</option>
                </select>
            </div>

            <label>{l s='Printer connect : ' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select id="mod_connect"
                        name="format_printer_connect" {if $service_type == "station_dat"} disabled class="disabled e-print" {else} class="e-print" {/if}>
                    <option value="usb" {if $format_printer_connect == "usb" || $format_hide_network != 'true'} selected="selected"{/if}>{l s='USB'    mod='dpdfrance'}</option>
                    <option value="ip" {if $format_printer_connect == "ip" && $format_hide_network == 'true'} selected="selected"{/if} {if $format_hide_network != 'true'}style="display: none;"{/if}>{l s='Network'    mod='dpdfrance'}</option>
                </select>
            </div>
            <br/>

            <label>{l s='Printer port : ' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <input name="format_printer_port"
                       type="text" {if $service_type == "station_dat" || $format_printer_connect == "usb" || $format_hide_network != "true"} disabled class="disabled e-print" {else} class="e-print" {/if}
                       value="{$format_printer_port|escape:'htmlall':'UTF-8'}"/>
            </div>
            <br/>

            <label>{l s='Printer ip : ' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <input name="format_printer_ip" type="text"
                        {if $service_type == "station_dat" || $format_printer_connect == "usb" || $format_hide_network != "true"}
                            disabled class="disabled e-print" {else} class="e-print"
                        {/if}
                       value="{$format_printer_ip|escape:'htmlall':'UTF-8'}"
                />
            </div>
            <br/>

            <label>{l s='Format mod : ' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select id="mod_format" name="format_mod"
                        {if $service_type != "e_print"} disabled class="disabled e-print" {else} class="e-print" {/if}
                >
                    <option value="zpl" {if $format_mod == "zpl" } selected="selected"{/if} {if $format_printer_connect != 'ip' || $format_hide_network != 'true'} style="display: none;" {/if}>{l s='ZPL' mod='dpdfrance'}</option>
                    <option value="epl" {if $format_mod == "epl" } selected="selected"{/if} {if $format_printer_connect != 'ip' || $format_hide_network != 'true'} style="display: none;" {/if}>{l s='EPL' mod='dpdfrance'}</option>
                    <option value="pdf" {if $format_mod == "pdf" || $format_printer_connect != 'ip' || $format_hide_network == 'true'} selected="selected"{/if}>{l s='PDF' mod='dpdfrance'}</option>
                </select>
            </div>
            <br/>

            <label>{l s='Format print : ' mod='dpdfrance'}<br/></label>
            <div class="margin-form">
                <select id="print_format" name="format_print"
                        {if $service_type != "e_print"} disabled class="disabled e-print" {else} class="e-print" {/if}
                >
                    <option id="a4" value="a4"
                            {if $format_print == "a4" && $format_mod == "pdf" } selected="selected"{/if}
                            {if $format_mod != 'pdf' && $format_printer_connect == 'ip'} style="display: none;" {/if}>
                        {l s='A4' mod='dpdfrance'}
                    </option>
                    <option id="a6"
                            value="a6" {if $format_print == "a6" || $format_mod != "pdf"} selected="selected"{/if}>
                        {l s='A6' mod='dpdfrance'}
                    </option>
                </select>
            </div>
            <br/>

            <div class="text-center">
                <a size="6" class="button" href="javascript:void(0)"
                   onclick="$('#onglet3').click();">
                    {l s='Previous' mod='dpdfrance'}
                </a>
                <a size="6" class="button" href="javascript:void(0)"
                    onclick="$('#onglet6').click();">
                    {l s='Next' mod='dpdfrance'}
                </a>
            </div>
            <br/>
        </div>

        <!-- (???) Tab Gestion des label -->
        <div id="gestion_label" style="display:none;">
            <br/>
            <span class="section_title_alt">{l s='Orders management' mod='dpdfrance'}</span>
            <br/><br/>
            <div class="text-center">
                <a size="6" class="button" href="javascript:void(0)"
                   onclick="$('#onglet4').click();">
                    {l s='Previous' mod='dpdfrance'}
                </a>
                <a size="6" class="button" href="javascript:void(0)"
                   onclick="$('#onglet6').click();">
                    {l s='Next' mod='dpdfrance'}
                </a>
            </div>
            <br/>
        </div>

        <!-- (#onglet6) Tab Recapitulatif -->
        <div id="recap" style="display:none;">
            <br/><br/>
            <strong>
                <p class="text-center">{l s='You\'re all set!' mod='dpdfrance'}</p>
            </strong>
            <br/><br/>

            <div class="text-center">
                <input id="save_settings_button" type="submit" name="submitRcReferer"
                       value="{l s='Save settings' mod='dpdfrance'}" class="button">
            </div>
            <br/>

            <div class="text-center">
                <a size="6" class="button" href="javascript:void(0)" onclick="$('#onglet4').click();">
                    {l s='Return to configuration' mod='dpdfrance'}
                </a>
            </div>
            <br/><br/>
        </div>
    </fieldset>
</form>
