<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWkT2YgU\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWkT2YgU/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerWkT2YgU.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerWkT2YgU\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerWkT2YgU\appAppKernelProdContainer([
    'container.build_hash' => 'WkT2YgU',
    'container.build_id' => '0ea75f88',
    'container.build_time' => 1686034743,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWkT2YgU');
