<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEYqUHrZ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEYqUHrZ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerEYqUHrZ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerEYqUHrZ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerEYqUHrZ\appAppKernelProdContainer([
    'container.build_hash' => 'EYqUHrZ',
    'container.build_id' => 'ab006969',
    'container.build_time' => 1686043783,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEYqUHrZ');
