<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Api\EventBusSyncClient' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Api\\EventBusSyncClient'] = new \PrestaShop\Module\PsEventbus\Api\EventBusSyncClient(($this->services['ps_eventbus.link'] ?? $this->load('getPsEventbus_LinkService.php')), ($this->services['PrestaShop\\PsAccountsInstaller\\Installer\\Facade\\PsAccounts'] ?? $this->load('getPsAccountsService.php')), 'https://eventbus-sync.psessentials.net');
