<?php
/**
 * Copyright 2023 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2023 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
require_once dirname(__FILE__, 3) . '/config/config.inc.php';
require_once dirname(__FILE__, 3) . '/init.php';
require_once __DIR__ . '/dpdfrance.php';

$params = [
    'order'             => Tools::getValue('order'),
    'address1'          => Tools::getValue('address'),
    'address_id'        => Tools::getValue('address_id'),
    'carrier_id'        => Tools::getValue('carrier_id'),
    'postcode'          => Tools::getValue('zipcode'),
    'city'              => Tools::getValue('city'),
    'pudo_id'           => Tools::getValue('pudo_id'),
    'gsm_dest'          => Tools::getValue('gsm_dest'),
    'action'            => Tools::getValue('action'),
    'dpdfrance_cart_id' => Tools::getValue('dpdfrance_cart_id'),
    'zip'               => Tools::getValue('zip'),
    'street'            => Tools::getValue('street'),
    'phone'             => Tools::getValue('phone'),
    'return'            => Tools::getValue('return'),
    'insurrance'        => Tools::getValue('insurrance'),
    'weights'           => Tools::getValue('weights'),
];

$result = null;
if ($action = Tools::getValue('action_ajax_dpdfrance')) {
    switch ($action) {
        case 'ajaxUpdatePoints':
            $result = Module::getInstanceByName('dpdfrance')->ajaxUpdatePoints($params);
            break;
        case 'ajaxRegisterGsm':
            $result = json_encode(Module::getInstanceByName('dpdfrance')->ajaxRegisterGsm());
            break;
        case 'ajaxUpdateShipping':
            $result = json_encode(Module::getInstanceByName('dpdfrance')->ajaxUpdateShipping());
            break;
        case 'ajaxGetGsmFromSelectedAddress':
            $result = Module::getInstanceByName('dpdfrance')->ajaxGetGsmFromSelectedAddress($params);
            break;
        case 'ajaxGetLeadtime':
            $result = Module::getInstanceByName('dpdfrance')->ajaxGetLeadtime($params);
            break;
        case 'ajaxRegisterPudo':
            $result = json_encode(Module::getInstanceByName('dpdfrance')->ajaxRegisterPudo());
            break;
        case 'ajaxRefreshListPdf':
            $result = json_encode(Module::getInstanceByName('dpdfrance')->ajaxRefreshListPdf());
            break;
        case 'getAddressOrder':
            $result = Module::getInstanceByName('dpdfrance')->ajaxGetAddressOrder($params);
            break;
        case 'setAddressOrder':
            $result = Module::getInstanceByName('dpdfrance')->ajaxSetAddressOrder($params);
            break;
        default:
            $result = '';
            break;
    }
}

echo $result;