<?php
/**
 * Copyright 2023 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2023 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
if (!defined('_PS_VERSION_')) {
    exit;
}

use PrestaShop\Module\DPDFrance\Util\DPDTools;

/**
 * @return bool
 * @throws PrestaShopDatabaseException
 */
function upgrade_module_6_1_4()
{
    // Suppression des anciennes clés de configuration qui ne seront plus utilisées
    Configuration::deleteByName('DPDFRANCE_WEBTRACE_URL');
    Configuration::deleteByName('DPDFRANCE_API_URL');

    // Nouveau système de cryptage des données en base
    DPDTools::generatePrivateKeyFile();

    $oldEncodedConfigKeys = [
        'DPDFRANCE_API_LOGIN',
        'DPDFRANCE_API_PASSWORD',
        'DPDFRANCE_WEBTRACE_LOGIN',
        'DPDFRANCE_WEBTRACE_PASSWORD',
    ];

    foreach ($oldEncodedConfigKeys as $oldEncodedConfigKey) {
        $cryptedValue = Configuration::get($oldEncodedConfigKey);
        if (!empty($cryptedValue)) {
            $decryptedValue = DPDTools::decrypt($cryptedValue, 'DPDFrancePrestashopModule');

            // Enregistrement de la valeur avec le nouvel encryptage
            // (on utilise la Configuration Prestashop)
            Configuration::updateValue($oldEncodedConfigKey, DPDTools::encrypt($decryptedValue));
        }
    }

    // Intégration de GEOLABEL
    DB::getInstance()->execute(
        'ALTER TABLE `' . _DB_PREFIX_ . 'dpdfrance_order` CHANGE `id_shipment_number_dpd` `id_shipment_number_dpd` '
        . 'VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL'
    );
    DB::getInstance()->execute(
        'ALTER TABLE `' . _DB_PREFIX_ . 'dpdfrance_order` CHANGE `id_retour_order_dpd` `id_retour_order_dpd` '
        . 'VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL'
    );

    // Suppression des anciens fichiers devenus obsolètes ou déplacés
    Tools::deleteDirectory(_PS_MODULE_DIR_ . 'dpdfrance/classes');
    Tools::deleteDirectory(_PS_MODULE_DIR_ . 'dpdfrance/vendor/PDFMerger-master');
    Tools::deleteFile(_PS_MODULE_DIR_ . 'dpdfrance/en.php');
    Tools::deleteFile(_PS_MODULE_DIR_ . 'dpdfrance/es.php');
    Tools::deleteFile(_PS_MODULE_DIR_ . 'dpdfrance/fr.php');
    Tools::deleteDirectory(_PS_MODULE_DIR_ . 'dpdfrance/src/utils');
    Tools::deleteDirectory(_PS_MODULE_DIR_ . 'dpdfrance/src/Utils');

    return true;
}
