<?php
/**
 * Copyright 2023 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2023 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
if (!defined('_PS_VERSION_')) {
    exit;
}

function upgrade_module_6_1_1()
{
    $dpd = new DPDFrance();
    $dpd->installConfigDB();

    $fieldsDescription = [
        'id_order'               => ['null' => false, 'type' => 'int(10) unsigned'],
        'id_order_dpd'           => ['null' => false, 'type' => 'varchar(50)'],
        'id_retour_order_dpd'    => ['null' => false, 'type' => 'varchar(20)'],
        'id_shipment_number_dpd' => ['null' => false, 'type' => 'varchar(50)'],
        'error_message'          => ['null' => true, 'type' => 'text'],
        'override_return_street' => ['null' => true, 'type' => 'varchar(35)'],
        'override_return_zip'    => ['null' => true, 'type' => 'varchar(10)'],
        'override_return_city'   => ['null' => true, 'type' => 'varchar(35)'],
        'override_return_phone'  => ['null' => true, 'type' => 'varchar(30)'],
        'return_print'           => ['null' => true, 'type' => 'varchar(30)'],
    ];

    $fields = [
        'id_order'               => true,
        'id_order_dpd'           => true,
        'id_retour_order_dpd'    => true,
        'id_shipment_number_dpd' => true,
        'error_message'          => true,
        'override_return_street' => true,
        'override_return_zip'    => true,
        'override_return_city'   => true,
        'override_return_phone'  => true,
        'return_print'           => true,
    ];
    $sql = 'DESCRIBE  ' . _DB_PREFIX_ . 'dpdfrance_order';
    $results = DB::getInstance()->executeS($sql);

    foreach ($results as $field) {
        if ($fields[$field['Field']]) {
            $fields[$field['Field']] = false;
        }
    }
    foreach ($fields as $key => $field) {
        if ($field) {
            $sql = 'ALTER TABLE ' . _DB_PREFIX_ . 'dpdfrance_order
                    ADD ' . $key . ' ' . $fieldsDescription[$key]['type'];
            if (!$fieldsDescription[$key]['null']) {
                $sql .= ' NOT NULL';
            }

            DB::getInstance()->execute($sql);
        }
    }

    $dpd->updateModuleTab();

    return true;
}
