{**
 * Copyright 2023 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2023 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *}

{literal}
    <script type='text/javascript'>
        $(document).ready(function () {
            $('.page-title').prepend('<img src="../modules/dpdfrance/views/img/admin/admin.png"/>')
            $('.marquee').marquee(
                {
                    duration        : 20000,
                    gap             : 50,
                    delayBeforeStart: 0,
                    direction       : 'left',
                    duplicated      : true,
                    pauseOnHover    : true,
                }
            );
            $('a.popup').fancybox(
                {
                    'hideOnContentClick': true,
                    'padding'           : 0,
                    'overlayColor'      : '#D3D3D3',
                    'overlayOpacity'    : 0.7,
                    'width'             : 1024,
                    'height'            : 640,
                    'type'              : 'iframe',
                }
            );
            jQuery.expr[':'].contains = function (a, i, m) {
                return jQuery(a).text().toUpperCase().indexOf(m[3].toUpperCase()) >= 0;
            };
            $("#tableFilter").keyup(function () {
                //split the current value of tableFilter
                var data = this.value.split(";");
                //create a jquery object of the rows
                var jo   = $("#fbody").find("tr");
                if (this.value == "") {
                    jo.show();
                    return;
                }
                //hide all the rows
                jo.hide();

                //Recusively filter the jquery object to get results.
                jo.filter(function (i, v) {
                    var t = $(this);
                    for (var d = 0; d < data.length; ++d) {
                        if (t.is(":contains('" + data[d] + "')")) {
                            return true;
                        }
                    }
                    return false;
                })
                    //show the rows that match.
                  .show();
            }).focus(function () {
                this.value = "";
                $(this).css({"color": "black"});
                $(this).unbind('focus');
            }).css({"color": "#C0C0C0"});

            if (typeof dpdfrance_dev_badge !== 'undefined') {
                $('h1.page-title').append(dpdfrance_dev_badge);
            }
        });

        function checkallboxes(ele) {
            var checkboxes = $("#fbody").find(".checkbox:visible");
            if (ele.checked) {
                for (var i = 0; i < checkboxes.length; i++) {
                    if (typeof checkboxes[i] !== "undefined" && checkboxes[i].type === 'checkbox' && !$('#' + checkboxes[i].id).is(":disabled")) {
                        checkboxes[i].checked = true;
                    }
                }
            } else {
                for (var i = 0; i < checkboxes.length; i++) {
                    if (checkboxes[i].type == 'checkbox') {
                        checkboxes[i].checked = false;
                    }
                }
            }
        }
    </script>
{/literal}

<div class="dpdfrance_content">
    {if !isset($stream.error) || (isset($stream.error) && !$stream.error)}
        <fieldset id="fieldset_rss">
            <legend>
                <a href="javascript:void(0)"
                   onclick="$(&quot;#zonemarquee&quot;).toggle(&quot;fast&quot;, function() {literal}{}{/literal});">
                    <img src="../modules/dpdfrance/views/img/admin/rss_icon.png"/>
                    {l s='DPD News (show/hide)' mod='dpdfrance'}
                </a>
            </legend>
            <div id="zonemarquee">
                <div id="marquee" class="marquee">
                    {foreach from=$stream item=item key=key}
                        <strong style="color:red;">{$item.category|escape:'htmlall':'UTF-8'}
                            > {$item.title|escape:'htmlall':'UTF-8'} : </strong>
                        {$item.description|escape:'htmlall':'UTF-8'}
                    {/foreach}
                </div>
            </div>
        </fieldset>
        <br/>
        <br/>
    {/if}

    {$msg|escape:'quotes':'UTF-8'}

    <div id="fieldset_grid">
        {if !isset($order_info.error) || (isset($order_info.error) && !$order_info.error)}
        <input id="tableFilter" placeholder="{l s='Search something, separate values with ; ' mod='dpdfrance'}"/>
        <img id="filtericon" src="../modules/dpdfrance/views/img/admin/search.png"/><br/><br/>
        <form
                {* Why do we need to disable all inputs where the order row checkboxes are not checked ? *}
                {*{literal}
                    onsubmit="
                        $('input:checkbox:not(:checked)').each(function() {
                            if(typeof $(this).data('id') !== 'undefined'){
                                  $('.parcelweight-'+$(this).data('id')).prop('disabled', true);
                            }
                        });
                        "
                {/literal}*}
                id="exportform" action="index.php?tab=AdminDPDFrance&token={$token|escape:'htmlall':'UTF-8'}" method="POST"
                enctype="multipart/form-data">
            <body>
            <table style="width: 100%;">
                <thead>
                <tr>
                    <th class="hcheckexport"><input type="checkbox" onchange="checkallboxes(this)"/></th>
                    <th class="hid text-center">ID</th>
                    <th class="href text-center">{l s='Reference' mod='dpdfrance'}</th>
                    <th class="hdate text-center">{l s='Date of order' mod='dpdfrance'}</th>
                    <th class="hnom text-center">{l s='Recipient' mod='dpdfrance'}</th>
                    <th class="htype text-center">{l s='Service' mod='dpdfrance'}</th>
                    <th class="hpr text-center">{l s='Destination' mod='dpdfrance'}</th>
                    {if $service != "e_print"}
                        <th class="hpoids text-center">{l s='Weight' mod='dpdfrance'}</th>
                    {/if}
                    <th colspan="2" class="hprix text-center">
                        {l s='Amount' mod='dpdfrance'}<br/>
                        <span style="font-size:10px;">{l s='(tick to insure<br/>this parcel)' mod='dpdfrance'}</span>
                    </th>
                    {if $dpdfrance_retour_option !== 0}
                        <th class="hretour text-center">{l s='Allow return' mod='dpdfrance'}</th>
                    {/if}
                    <th class="hstatutcommande text-center">{l s='Order status' mod='dpdfrance'}</th>
                    <th class="hstatutcolis text-center">{l s='Parcel trace' mod='dpdfrance'}</th>

                    {if $service == "e_print"}
                        <th class="hpoidslabel text-center">{l s='Weight' mod='dpdfrance'}</th>
                        <th class="hlabelprint text-center">{l s='Print' mod='dpdfrance'}</th>
                        <th class="hstatusLabel text-center">{l s='Status label' mod='dpdfrance'}</th>
                    {/if}
                </tr>
                </thead>
                <tbody id="fbody">
                {foreach from=$order_info item=order}
                    <tr>
                        <td>
                            <input id="checkbox_{$order.id|escape:'htmlall':'UTF-8'}"
                                   class="checkbox checkbox-id"
                                   type="checkbox"
                                   name="checkbox[]" {$order.checked|escape:'htmlall':'UTF-8'}
                                   data-id="{$order.id|escape:'htmlall':'UTF-8'}"
                                   value="{$order.id|escape:'htmlall':'UTF-8'}">
                        </td>
                        <td class="id text-center">{$order.id|escape:'htmlall':'UTF-8'}</td>
                        <td class="ref text-center">{$order.reference|escape:'htmlall':'UTF-8'}</td>
                        <td class="date text-center">{$order.date|escape:'htmlall':'UTF-8'}</td>
                        <td class="nom text-center">{$order.nom|escape:'htmlall':'UTF-8'}</td>
                        <td class="type text-center">{$order.type|escape:'quotes':'UTF-8'}</td>
                        <td class="pr text-center">{$order.address|escape:'quotes':'UTF-8'}</td>
                        {if $service != "e_print"}
                            <td class="poids text-center">
                                <input name="parcelweight[{$order.id|escape:'htmlall':'UTF-8'}]" type="text"
                                       value="{$order.poids|escape:'htmlall':'UTF-8'}"/>
                                {$order.weightunit|escape:'htmlall':'UTF-8'}
                            </td>
                        {/if}
                        <td class="prix text-center">{$order.prix|escape:'htmlall':'UTF-8'}</td>
                        <td class="advalorem">
                            <input class="advalorem" type="checkbox"
                                   name="advalorem[]" {$order.advalorem_checked|escape:'htmlall':'UTF-8'}
                                   value="{$order.id|escape:'htmlall':'UTF-8'}">
                        </td>
                        {if $dpdfrance_retour_option !== 0}
                            <td class="retour text-center">
                                {if $order.country == 'FR'}
                                    <input class="retour" type="checkbox"
                                           name="retour[{$order.id|escape:'htmlall':'UTF-8'}]" {$order.retour_checked|escape:'htmlall':'UTF-8'}
                                           value="{$order.id|escape:'htmlall':'UTF-8'}">
                                {/if}
                            </td>
                        {/if}
                        <td class="statutcommande text-center">
                            {$order.statut|escape:'quotes':'UTF-8'}
                        </td>
                        <td class="statutcolis text-center">
                            <a href="javascript:void(0)"
                               onclick="window.open('https://trace.dpd.fr/tracex_{if $dpdfrance_auto_update_option == 3}{$order.id|escape:'htmlall':'UTF-8'}{else}{$order.reference|escape:'htmlall':'UTF-8'}{/if}_{$order.depot_code|escape:'htmlall':'UTF-8'}{$order.shipper_code|escape:'htmlall':'UTF-8'}','','width=1024,height=768,top=30,left=20')">
                                {$order.dernier_statut_colis|escape:'quotes':'UTF-8'}
                            </a>
                        </td>
                        {if $service == "e_print"}
                            <td class="poidslabel text-center">
                                {if !$order.expediee}
                                    <div class="tooltip_weight">{l s='Please enter a weight value' mod='dpdfrance'}</div>
                                    <div>
                                        <label>{l s='Parcel' mod='dpdfrance'} 1</label>
                                        <input class="parcelweight parcelweight-{$order.id|escape:'htmlall':'UTF-8'}"
                                               name="parcelweight[{$order.id|escape:'htmlall':'UTF-8'}][]" type="text"
                                               value="{$order.poids|escape:'htmlall':'UTF-8'}"
                                        />
                                        {$order.weightunit|escape:'htmlall':'UTF-8'}
                                    </div>
                                    <i class="icon-plus-sign add-weight pointer" data-number="1"
                                       data-id="{$order.id|escape:'htmlall':'UTF-8'}"
                                       data-unit="{$order.weightunit|escape:'htmlall':'UTF-8'}">
                                    </i>
                                    <i class="icon-minus-sign remove-weight pointer" style="display: none;" data-number="1"
                                       data-id="{$order.id|escape:'htmlall':'UTF-8'}"
                                       data-unit="{$order.weightunit|escape:'htmlall':'UTF-8'}">
                                    </i>
                                {/if}
                            </td>
                            <td class="labelprint text-center" id="labelprint_{$order.id|escape:'htmlall':'UTF-8'}">
                                {if !$order.expediee}
                                    <i title="{l s='Print' mod='dpdfrance'}"
                                       class="icon-print pointer {if !empty($order.labelprint) && $order.labelprint }text-success{/if} print-click"
                                       data-id="{$order.id|escape:'htmlall':'UTF-8'}">
                                    </i>
                                {/if}
                            </td>
                            <td class="statusLabel text-center">
                                {if !empty($order.statuslabel) && $order.statuslabel }
                                    <i class="icon-warning-sign text-danger" title="{$order.statustext|escape:'htmlall':'UTF-8'}"></i>
                                {/if}
                            </td>
                        {/if}
                    </tr>
                {/foreach}
                </tbody>
            </table>

            {* BUTTONS ROW*}
            <p>
                {if $service == "station_dat"}
                    <input type="submit" class="button" name="exportOrders"
                           value="{l s='Export selected orders to DPD Station' mod='dpdfrance'}"/>
                {/if}
                {if $service == "e_print"}
                    <input type="submit" class="button" id="exportLabel" name="exportLabel" formtarget="_blank"
                           value="{l s='Export label' mod='dpdfrance'}"/>
                {/if}
                <input type="submit" class="button" name="updateShippedOrders"
                       value="{l s='Update shipped orders' mod='dpdfrance'}"/>
                <input type="submit" class="button" name="updateDeliveredOrders"
                       value="{l s='Update delivered orders' mod='dpdfrance'}"/>
            </p>
            {if $service == "e_print"}
                <span class="key ">
                    <span class="row">
                        <i class="icon-print text-success"></i>
                        <span>{l s='Label already generate' mod='dpdfrance'}</span>
                    </span>
                    <span class="row">
                        <i class="icon-warning-sign text-danger"></i>
                        <span>{l s='Error for generate a label' mod='dpdfrance'}</span>
                    </span>
                </span>
            {/if}
        </form>
    </div>
    {else}
        <div class="alert-error">{l s='There are no orders' mod='dpdfrance'}</div>
    {/if}
</div>

<script>
    var multiParcelPrototype   = '<div><label>{l s='Parcel' mod='dpdfrance'} __number_parcel__</label> <input class="parcelweight parcelweight-__id_order__"  name="parcelweight[__id_order__][]" type="text" value="0.00" /> __unit_order__  </div>';
    var dpdfrance_base_dir     = "{$dpdfrance_base_dir|escape:'javascript':'UTF-8'}";
    var dpdfrance_token        = "{$dpdfrance_token|escape:'javascript':'UTF-8'}";
    var dpdfrance_usb_name     = "{$dpdfrance_usb_name|escape:'javascript':'UTF-8'}";
    var dpdfrance_mode_service = "{$service|escape:'javascript':'UTF-8'}";
    {if isset($dpdfrance_dev_badge)}
        var dpdfrance_dev_badge = '{$dpdfrance_dev_badge}';
    {/if}
</script>
