{**
 * Copyright 2023 DPD France S.A.S.
 *
 * This file is a part of dpdfrance module for Prestashop.
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this module to newer
 * versions in the future. If you wish to customize this module for
 * your needs please contact us at support.ecommerce@dpd.fr.
 *
 * @author    DPD France S.A.S. <support.ecommerce@dpd.fr>
 * @copyright 2023 DPD France S.A.S.
 * @license   http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *}

{literal}
<script type='text/javascript'>
    $(document).ready(function(){
        $('.page-title').prepend('<img src="../modules/dpdfrance/views/img/admin/admin.png"/>')
        $('.marquee').marquee({
            duration: 20000,
            gap: 50,
            delayBeforeStart: 0,
            direction: 'left',
            duplicated: true,
            pauseOnHover: true
        });
    $('a.popup').fancybox({
            'hideOnContentClick': true,
            'padding'           : 0,
            'overlayColor'      :'#D3D3D3',
            'overlayOpacity'    : 0.7,
            'width'             : 1024,
            'height'            : 640,
            'type'              :'iframe'
            });
        jQuery.expr[':'].contains = function(a, i, m) {
            return jQuery(a).text().toUpperCase().indexOf(m[3].toUpperCase()) >= 0;
        };
    $("#tableFilter").keyup(function () {
        //split the current value of tableFilter
        var data = this.value.split(";");
        //create a jquery object of the rows
        var jo = $("#fbody").find("tr");
        if (this.value == "") {
            jo.show();
            return;
        }
        //hide all the rows
        jo.hide();

        //Recusively filter the jquery object to get results.
        jo.filter(function (i, v) {
            var t = $(this);
            for (var d = 0; d < data.length; ++d) {
                if (t.is(":contains('" + data[d] + "')")) {
                    return true;
                }
            }
            return false;
        })
        //show the rows that match.
        .show();
        }).focus(function () {
            this.value = "";
            $(this).css({
                "color": "black"
            });
            $(this).unbind('focus');
        }).css({
            "color": "#C0C0C0"
        });

        if (typeof dpdfrance_dev_badge !== 'undefined') {
            $('h1.page-title').append(dpdfrance_dev_badge);
        }
    });

    function checkallboxes(ele) {
        var checkboxes = $("#fbody").find(".checkbox:visible");
        if (ele.checked) {
            for (var i = 0; i < checkboxes.length; i++) {
                if (checkboxes[i].type == 'checkbox') {
                    checkboxes[i].checked = true;
                }
            }
        } else {
            for (var i = 0; i < checkboxes.length; i++) {
                if (checkboxes[i].type == 'checkbox') {
                    checkboxes[i].checked = false;
                }
            }
        }
    }
</script>
{/literal}

<div class="dpdfrance_content">
    {if !isset($stream.error) || (isset($stream.error) && !$stream.error)}
        <fieldset id="fieldset_rss">
            <legend>
                <a href="javascript:void(0)"
                   onclick="$(&quot;#zonemarquee&quot;).toggle(&quot;fast&quot;, function() {literal}{}{/literal});"><img
                            src="../modules/dpdfrance/views/img/admin/rss_icon.png"/>
                    {l s='DPD News (show/hide)' mod='dpdfrance'}
                </a>
            </legend>
            <div id="zonemarquee">
                <div id="marquee" class="marquee">
                    {foreach from=$stream item=item key=key}
                        <strong style="color:red;">{$item.category|escape:'htmlall':'UTF-8'}
                            > {$item.title|escape:'htmlall':'UTF-8'} : </strong>
                        {$item.description|escape:'htmlall':'UTF-8'}
                    {/foreach}
                </div>
            </div>
        </fieldset>
        <br/><br/>
    {/if}

    {$msg|escape:'quotes':'UTF-8'}

    <div id="fieldset_grid">
    {if !isset($order_info.error) || (isset($order_info.error) && !$order_info.error)}
        <input id="tableFilter" placeholder="{l s='Search something, separate values with ; ' mod='dpdfrance'}"/>
        <img id="filtericon" src="../modules/dpdfrance/views/img/admin/search.png" alt="filtericon"/>
        <br/><br/>
        <form id="exportform" action="index.php?tab=AdminDPDFranceReturn&token={$token|escape:'htmlall':'UTF-8'}"
              method="POST" enctype="multipart/form-data">
            <body>
            <table style="width: 100%;">
                <thead>
                <tr>
                    <th class="hcheckexport">
                        <input style="display: none" type="checkbox" onchange="checkallboxes(this)"/>
                    </th>
                    <th class="hid text-center">ID</th>
                    <th class="href text-center">{l s='Reference' mod='dpdfrance'}</th>
                    <th class="hdate text-center">{l s='Date of order' mod='dpdfrance'}</th>
                    <th class="hnom text-center">{l s='Recipient' mod='dpdfrance'}</th>
                    <th class="htype text-center">{l s='Service' mod='dpdfrance'}</th>
                    <th class="hpr text-center">{l s='Destination' mod='dpdfrance'}</th>
                    <th class="hca text-center">{l s='Change Address' mod='dpdfrance'}</th>
                    <th class="hstatutcolis text-center">{l s='Parcel trace' mod='dpdfrance'}</th>
                    <th class="hlabelprint text-center">{l s='Print' mod='dpdfrance'}</th>
                    <th class="hstatusLabel text-center">{l s='Status label' mod='dpdfrance'}</th>

                </tr>
                </thead>
                <tbody id="fbody">

                {foreach from=$order_info item=order_return}
                    <tr>
                        <td>
                            <input style="display: none" id="checkbox_{$order_return.id|escape:'htmlall':'UTF-8'}"
                                   data-id="{$order_return.id|escape:'htmlall':'UTF-8'}" class="checkbox checkbox-id"
                                   type="checkbox" name="checkbox[]" value="{$order_return.id|escape:'htmlall':'UTF-8'}">
                        </td>
                        <td class="id text-center" style="min-width: 80px">{$order_return.id|escape:'htmlall':'UTF-8'}</td>
                        <td class="ref text-center">{$order_return.reference|escape:'htmlall':'UTF-8'}</td>
                        <td class="date text-center">{$order_return.date|escape:'htmlall':'UTF-8'}</td>
                        <td class="nom text-center">{$order_return.nom|escape:'htmlall':'UTF-8'}</td>
                        <td class="type text-center">{$order_return.type|escape:'quotes':'UTF-8'}</td>
                        <td class="pr text-center">{$order_return.address|escape:'quotes':'UTF-8'}</td>
                        <td class="ca text-center">
                            <a href="#" class="btn btn-primary modal-form-change" data-toggle="modal"
                               data-target="#formChange" data-order="{$order_return.id|escape:'htmlall':'UTF-8'}">
                                {l s='Update Address' mod='dpdfrance'}
                            </a>
                        </td>
                        <td class="statutcolis text-center">
                            <a href="javascript:void(0)" onclick="window.open('https://trace.dpd.fr/tracex_{$order_return.reference|escape:'htmlall':'UTF-8'}_{$order_return.depot_code|escape:'htmlall':'UTF-8'}{$order_return.shipper_code|escape:'htmlall':'UTF-8'}','','width=1024,height=768,top=30,left=20')">{$order_return.dernier_statut_colis|escape:'quotes':'UTF-8'}</a>
                        </td>
                        <td class="labelprint text-center" id="labelprint_{$order_return.id|escape:'htmlall':'UTF-8'}">
                            {if $order_return.arrived }
                                {if !empty($order_return.labelprint) && $order_return.labelprint }
                                    <i class="icon-print pointer text-success print-click"
                                       data-id="{$order_return.id|escape:'htmlall':'UTF-8'}"></i>
                                {else}
                                    <i class="icon-print pointer print-click"
                                       data-id="{$order_return.id|escape:'htmlall':'UTF-8'}"></i>
                                {/if}
                            {/if}
                        </td>
                        <td class="statusLabel text-center">
                            {if !empty($order_return.statuslabel) && $order_return.statuslabel }
                            <i class="icon-warning-sign text-danger" title="{$order_return.statustext|escape:'htmlall':'UTF-8'}"></i>
                            {/if}
                        </td>

                    </tr>
                {/foreach}
                </tbody>
            </table>
            <p>
                <input type="submit" style="display: none" class="button" id="exportLabel" name="exportLabel"
                       formtarget="_blank" value="{l s='Export label' mod='dpdfrance'}"/>
            </p>

            <span class="key ">
                <span class="row">
                    <i class="icon-print text-success"></i>
                    <span>{l s='Label already generate' mod='dpdfrance'}</span>
                </span>
                <span class="row">
                    <i class="icon-warning-sign text-danger"></i>
                    <span>{l s='Error for generate a label' mod='dpdfrance'}</span>
                </span>
            </span>
        </form>
    </div>
    {else}
        <div class="alert warn">{l s='There are no orders' mod='dpdfrance'}</div>
    {/if}
</div>

<!-- Modal -->
<div class="modal fade" id="formChange" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{l s='Update return address' mod='dpdfrance'}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="form-change" action="index.php?tab=AdminDPDFranceReturn&token={$token|escape:'htmlall':'UTF-8'}&action=changeReturnAddress" method="POST" enctype="multipart/form-data">
                    <div class="row">
                        <div class="col-sm-12 form-group-sm">
                            <input class="form-control" placeholder="{l s='Street' mod='dpdfrance'}" type="text" name="street" id="street" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 form-group-sm">
                            <input class="form-control" min="5" max="5" placeholder="{l s='Zip Code' mod='dpdfrance'}" type="text" name="zip" id="zip" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 form-group-sm">
                            <input class="form-control" placeholder="{l s='City' mod='dpdfrance'}" type="text" name="city" id="city" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 form-group-sm">
                            <input class="form-control" placeholder="{l s='Phone' mod='dpdfrance'}" type="text" name="phone" id="phone" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="close-button" data-dismiss="modal">{l s='Close' mod='dpdfrance'}</button>
                <button type="button" class="btn btn-primary" id="save" data-order="">{l s='Save change' mod='dpdfrance'}</button>
            </div>
        </div>
    </div>
</div>

<script>
    var dpdfrance_base_dir = "{$dpdfrance_base_dir|escape:'javascript':'UTF-8'}";
    var dpdfrance_token    = "{$dpdfrance_token|escape:'javascript':'UTF-8'}";
    {if isset($dpdfrance_dev_badge)}
        var dpdfrance_dev_badge = '{$dpdfrance_dev_badge}';
    {/if}
</script>
